name: row_notes
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.0-285.0.dev <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  ###
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  dotted_border: ^2.0.0+3
  flutter_native_splash: ^2.3.1
  image_picker: ^1.0.1
  ###
  cupertino_icons: ^1.0.2
flutter_native_splash:
  image: "assets/logo.png"
  color: "#1e1e1e"
  # dart run flutter_native_splash:create
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ###
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  ###
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik-Medium.ttf
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Medium.ttf
